import type { CharadesWordEntry } from "../../shared/types";

// This file is generated by scripts/generate-charades-word-bank.mjs
// Generated at: 2026-03-11T08:03:27.922Z
export const CHARADES_WORD_BANK: CharadesWordEntry[] = [
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "牙刷"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "牙膏"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "毛巾"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "脸盆"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "香皂"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "洗发水"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "沐浴露"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "拖鞋"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "雨伞"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "水杯"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "保温杯"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "饭碗"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "筷子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "勺子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "叉子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "盘子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "锅盖"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "平底锅"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "电饭煲"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "微波炉"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "冰箱"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "空调"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "风扇"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "台灯"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "手电筒"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "充电器"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "插线板"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "电脑"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "键盘"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "鼠标"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "耳机"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "音箱"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "手机"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "平板"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "相机"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "书包"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "背包"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "行李箱"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "钱包"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "钥匙"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "门锁"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "窗帘"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "床单"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "枕头"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "被子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "沙发"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "桌子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "椅子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "衣架"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "洗衣机"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "烘干机"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "吹风机"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "剃须刀"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "镜子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "梳子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "剪刀"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "胶水"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "橡皮"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "铅笔"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "圆珠笔"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "钢笔"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "尺子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "本子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "便签"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "书签"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "日历"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "闹钟"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "手表"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "眼镜"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "太阳镜"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "口罩"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "帽子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "围巾"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "手套"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "袜子"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "外套"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "衬衫"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "短袖"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "牛仔裤"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "运动鞋"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "拖把"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "扫把"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "簸箕"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "垃圾桶"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "纸巾"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "湿巾"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "洗洁精"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "抹布"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "海绵"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "花瓶"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "绿萝"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "仙人掌"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "盆栽"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "地毯"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "门铃"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "遥控器"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "投影仪"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "路由器"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "电池"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "灯泡"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "茶壶"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "茶杯"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "咖啡杯"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "奶茶"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "果汁"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "矿泉水"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "饼干"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "薯片"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "蛋挞"
  },
  {
    "category": "日常",
    "difficulty": "easy",
    "word": "面条"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "米饭"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "鸡蛋"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "番茄"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "黄瓜"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "土豆"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "白菜"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "胡萝卜"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "苹果"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "香蕉"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "西瓜"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "草莓"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "葡萄"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "橙子"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "芒果"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "菠萝"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "火锅"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "炒饭"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "包子"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "馒头"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "饺子"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "馄饨"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "披萨"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "汉堡"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "寿司"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "烤鸭"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "牛排"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "煎饼"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "麻辣烫"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "烤串"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "奶酪"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "酸奶"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "冰淇淋"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "巧克力"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "蛋糕"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "月饼"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "粽子"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "年糕"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "汤圆"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "芝麻糊"
  },
  {
    "category": "日常",
    "difficulty": "medium",
    "word": "豆浆"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "信鸽"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "黄蜂"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "水母"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "野猫"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "宠物狗"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "母狗"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "毛毛虫"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "猎豹"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "犀牛"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "萨摩"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "狼狗"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "喜鹊"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "梅花鹿"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "牡蛎"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "毛驴"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "母牛"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "野牛"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "多宝鱼"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "小蜜蜂"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "猿人"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "猎狗"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "小尾寒羊"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "金枪鱼"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "大黄蜂"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "墨鱼"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "扇贝"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "毛滴虫"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "小雀"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "苏眉"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "狼犬"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "黄粉虫"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "野菊花"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "夜鹰"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "导盲犬"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "猫科动物"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "利木赞牛"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "目鱼"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "文金"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "越前龙"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "野驴"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "瓢虫"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "九间"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "软体动物"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "鹡鸰"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "蝇蛆"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "家鸡"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "河蚌"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "全蝎"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "刺参"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "灵长类动物"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "囊虫"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "杜泊绵羊"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "小鲤"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "毛蟹"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "鹩哥"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "喷毒眼镜蛇"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "文蛤"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "斗牛犬"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "野牦牛"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "寄居蟹"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "鹦哥"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "画眉鸟"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "苏格兰牧羊犬"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "台鸽"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "狮子狗"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "抹香鲸"
  },
  {
    "category": "动物",
    "difficulty": "medium",
    "word": "桃花水母"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "牛奶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "面包"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "豆腐"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "萝卜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "点心"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "海鲜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "葡萄酒"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "羊肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "柠檬"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "淀粉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "酱油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "核桃"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "饮用水"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鸳鸯"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "青团"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "白糖"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "方便面"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "可口可乐"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "乙醇"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "红柿"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "普洱茶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "西红柿"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "茅台"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鱼类"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "磷酸"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "托盘"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "青梅"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "沙拉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "奶油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "石膏"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "石榴"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "豆油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "青菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "肉眼"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "木耳"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "铁板"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "生姜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "黄豆"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "三七"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "烤肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "大肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "洋葱"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "娃哈哈"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "香菇"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "松花"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "川菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "海带"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "五粮液"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鱿鱼"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "山药"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "聚乙烯"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "橄榄油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "冬瓜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "果后"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "韭菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "纯净水"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "狗肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "甘露"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "冰点"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "豆芽"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "释迦"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "比萨"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "糖水"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "胡萝卜素"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "香草"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "藏宝"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "泡菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "铁观音"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鱼头"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鲜奶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "盐酸"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "油条"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "叶酸"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "虾米"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "防腐剂"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "稻谷"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "粤菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "磷脂"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "健力"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "香肠"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "桔子"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "烟熏"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "花生油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "康师傅"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "健力宝"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "香菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鸡尾酒"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "全聚德"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "咖啡因"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "劲风"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "二氧化硫"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "猪肝"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "威士忌"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "冷面"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "面皮"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "烧肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "咖喱"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "山鸡"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "紫菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "百事可乐"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "米线"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "黄油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "米粥"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "乌龙茶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "烤箱"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "猕猴桃"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "家常菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "果肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "冰激凌"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "米面"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "三明治"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "带鱼"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "大丰收"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "千张"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "芭蕉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "生菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "酥油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "肉干"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "牛肉面"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "抗氧化剂"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "清汤"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "湘菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "莱姆"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "露丝"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "耗油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "海盐"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "黑豆"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "腊肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "臭豆腐"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "糖浆"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "寸金"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "柠檬汁"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "白果"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "天麻"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "老酒"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "富春"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "花菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "贵州茅台"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "油茶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "雪梨"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "布丁"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "铁蛋"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "杂碎"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "咖啡豆"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "红葡萄酒"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "明胶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "酒肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "棉花糖"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "杜康"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "滑石粉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "柑桔"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "源通"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "二锅头"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "葡萄干"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "莲藕"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "凉粉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "梨子"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "芥末"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "芝士"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "芦笋"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "碳酸钙"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "烤鱼"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "水蜜桃"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "油酸"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "乙酸"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "培根"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "炸食"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "柠檬酸"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "扣肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "牛乳"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "杏子"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "凉菜"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "掌上明珠"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "果胶"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "茶汤"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "白油"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "核桃仁"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "鸭肉"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "草鱼"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "满汉全席"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "番茄酱"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "大富豪"
  },
  {
    "category": "食物",
    "difficulty": "medium",
    "word": "干红"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "不明觉厉"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "然并卵"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "画美不看"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "人艰不拆"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "累觉不爱"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "爷青结"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "十动然拒"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "蓝瘦香菇"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "网红"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "剁手党"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "脑洞大开"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "油腻"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "高富帅"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "粉丝"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "飞友"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "内卷"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "躺平"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "精神小伙"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "主理人"
  },
  {
    "category": "网络热词",
    "difficulty": "easy",
    "word": "搭子"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "破防"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "上头"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "下头"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "拿捏"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "整活"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "摆烂"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "冲浪"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "吃瓜"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "热搜"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "塌房"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "翻车"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "爆改"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "神仙"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "高能"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "卡点"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "打卡"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "种草"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "拔草"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "安利"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "同款"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "盲盒"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "开箱"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "测评"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "带货"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "秒杀"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "拼单"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "预售"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "尾款"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "下单"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "补货"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "断货"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "真香"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "离谱"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "逆天"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "无语"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "泪目"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "感动"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "治愈"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "氛围感"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "松弛感"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "仪式感"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "情绪价值"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "社恐"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "社牛"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "显眼包"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "电子榨菜"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "云旅游"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "云健身"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "云办公"
  },
  {
    "category": "流行语境",
    "difficulty": "easy",
    "word": "打工人"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "工具人"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "尾款人"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "搬砖"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "摸鱼"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "卷王"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "躺赢"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "天花板"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "地板价"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "人设"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "路人缘"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "反差感"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "拉满"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "回旋镖"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "嘴替"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "发疯"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "续命"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "回血"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "满血"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "空耳"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "梦幻联动"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "二创"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "改编"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "混剪"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "转场"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "高清"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "超清"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "弹幕"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "关注"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "点赞"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "收藏"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "转发"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "私信"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "同频"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "共鸣"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "代入感"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "沉浸式"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "碎片化"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "信息差"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "新手村"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "赛道"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "风口"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "闭环"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "增量"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "存量"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "复盘"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "对齐"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "拆解"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "方案"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "需求"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "排期"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "上线"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "回滚"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "降级"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "并发"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "延迟"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "卡顿"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "闪退"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "兼容"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "修复"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "优化"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "迭代"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "版本"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "热更新"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "缓存"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "日志"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "告警"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "容灾"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "备份"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "恢复"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "网络波动"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "负载均衡"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "自动化"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "可视化"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "数据看板"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "推荐算法"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "模型训练"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "算力"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "深度学习"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "机器学习"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "人工智能"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "大模型"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "提示词"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "数据标注"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "多模态"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "语音识别"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "图像识别"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "文本生成"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "智能助手"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "在线协作"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "知识库"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "搜索引擎"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "云存储"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "云服务"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "开源社区"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "开发者"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "产品经理"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "设计师"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "程序员"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "测试工程师"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "运维工程师"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "前端开发"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "后端开发"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "全栈开发"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "用户体验"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "交互设计"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "视觉设计"
  },
  {
    "category": "流行语境",
    "difficulty": "medium",
    "word": "信息架构"
  },
  {
    "category": "科技词",
    "difficulty": "medium",
    "word": "字符串"
  },
  {
    "category": "科技词",
    "difficulty": "medium",
    "word": "初始化"
  },
  {
    "category": "科技词",
    "difficulty": "medium",
    "word": "数组"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "加载"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "客户端"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "应用程序"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "自定义"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "配置文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "封装"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "字段"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "解决方案"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "编译器"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "重启"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "控件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "子类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "文件名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据结构"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据类型"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "构造函数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "解决方法"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "用户名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "头文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "命令行"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "实例化"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "递归"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "父类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "多线程"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "环境变量"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "右键"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "服务器端"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "生命周期"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "类名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "优先级"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "官网"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "上传"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "成员变量"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "程序运行"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "服务端"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "根目录"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "链表"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "文件系统"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "开发人员"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "嵌套"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "全局变量"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "内存空间"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "版本号"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "下载地址"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "后缀"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "构造方法"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "结点"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "源文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "局部变量"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "函数调用"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "复杂度"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "赋值"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "自动生成"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "时间复杂度"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "实现类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "堆栈"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "基类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "整型"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "函数返回"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "表单"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "运算符"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "只读"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "错误信息"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "寄存器"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "主线程"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据源"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "正则表达式"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "操作符"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "缩放"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "抽象类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "回调函数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "静态方法"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "返回结果"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "读取数据"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "显式"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "当前目录"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "变量名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "大小写"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "作用域"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "布局文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "包名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "创建对象"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "测试数据"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "端口号"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "复用"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "存储空间"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "重新启动"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "抛出异常"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "类库"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "代码实现"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "标识符"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "方法调用"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "直接访问"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "编程语言"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "业务逻辑"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "序列化"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "成员函数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据存储"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "可执行"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "快捷键"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "字节数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "设计模式"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "重定向"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "调用函数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "可执行文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "代码块"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "方法名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "参考资料"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "线程安全"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "主键"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "命名空间"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "调用方法"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "执行过程"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "工具类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据传输"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "预处理"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "获取数据"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "示例代码"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "文件路径"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "参数传递"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "重置"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "新版本"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "偏移量"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "重命名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "跨平台"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "文本文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "工作原理"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "开发环境"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "依赖关系"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "子目录"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "系统调用"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据集"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "类对象"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "发送消息"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "句柄"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "下划线"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "浮点数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "面向对象"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "日志文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "持久化"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "二维"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "配置信息"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "参数类型"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "资源文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "基本数据类型"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "绝对路径"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "打开文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "内存管理"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "安装包"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "静态变量"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "应用场景"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "基本类型"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "迭代器"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "软件开发"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "类继承"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "正常运行"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "存储数据"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "点击事件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "程序代码"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "目录结构"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "类型转换"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "构造器"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "多态"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "访问权限"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "二叉树"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "内存地址"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "内部类"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "监听器"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "分隔符"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据库连接"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "表名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "分页"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "冒号"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "十六进制"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "网络连接"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "修饰符"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "重新编译"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "开源项目"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "大数据"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "线程池"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "时间戳"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "元数据"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "属性设置"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "输入流"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "系统资源"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "双引号"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "内存分配"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "主机名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "用户界面"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "随机数"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "结果集"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "应用层"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "驱动程序"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "开发过程"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "运行环境"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数据处理"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "权重"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "泛型"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "文件大小"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "输出流"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "子节点"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "输入输出"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "升序"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "字节码"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "库文件"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "十进制"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "数组元素"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "离线"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "套接字"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "时间间隔"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "事件处理"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "推送"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "单线程"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "代码段"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "存储过程"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "类方法"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "加锁"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "扩展名"
  },
  {
    "category": "科技词",
    "difficulty": "hard",
    "word": "插入数据"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "坚定不移"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "全力以赴"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "丰富多彩"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "余波未平"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "脱颖而出"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "实事求是"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一如既往"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "众所周知"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一年一度"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "因地制宜"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "千方百计"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "息息相关"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "层出不穷"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "引人注目"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "当务之急"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "滥用职权"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "深入人心"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "解放思想"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "见义勇为"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "敲诈勒索"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "名不虚传"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "来之不易"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "名副其实"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "下落不明"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "坚持不懈"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "源源不断"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "络绎不绝"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "弄虚作假"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不可思议"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不正之风"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "小心翼翼"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "长治久安"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "如火如荼"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不折不扣"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "后顾之忧"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "纸醉金迷"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "力所能及"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "供不应求"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一目了然"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "显而易见"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "持之以恒"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "成千上万"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "大街小巷"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "可想而知"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "安居乐业"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "齐心协力"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "得天独厚"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一见钟情"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "艰苦奋斗"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "全心全意"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "独一无二"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不约而同"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "紧锣密鼓"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "五花八门"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一应俱全"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "应运而生"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "与众不同"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "触目惊心"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "屡见不鲜"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "无独有偶"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "行之有效"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不知不觉"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "大势所趋"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "千家万户"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "心有余悸"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不得而知"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "前所未有"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "迫不及待"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "雪上加霜"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "迫在眉睫"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "此起彼伏"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "脚踏实地"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "意想不到"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "错综复杂"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "无可厚非"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "源远流长"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "举一反三"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "循序渐进"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不遗余力"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不言而喻"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "讨价还价"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "深恶痛绝"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "三位一体"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "截然不同"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "记忆犹新"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "喜闻乐见"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "家喻户晓"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "日新月异"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "取而代之"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "莫名其妙"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "名列前茅"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "排忧解难"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "各式各样"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "玩忽职守"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "任重道远"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "奋发有为"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "举足轻重"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "比比皆是"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "卓有成效"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "落地生根"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "势在必行"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "史无前例"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "理所当然"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "耳熟能详"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "由来已久"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一模一样"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "厉行节约"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "恶性循环"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "铤而走险"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "举世瞩目"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "再接再厉"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "足不出户"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "翻天覆地"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "非同寻常"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "挨家挨户"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不翼而飞"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "参差不齐"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "水涨船高"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "沸沸扬扬"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "先发制人"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "轩然大波"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "土生土长"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "出人意料"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "统筹兼顾"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "明察暗访"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "刻不容缓"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "融为一体"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "焕然一新"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "以身作则"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "潜移默化"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "风口浪尖"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "有条不紊"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "归根结底"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "发扬光大"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "旗帜鲜明"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "万无一失"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "可见一斑"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一视同仁"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "相辅相成"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "淋漓尽致"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "耳目一新"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "不了了之"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "热火朝天"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "有目共睹"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "久而久之"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "视而不见"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "自强不息"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "以权谋私"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "继往开来"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "赞不绝口"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "义不容辞"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "未雨绸缪"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "一举一动"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "绳之以法"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "尽如人意"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "有所作为"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "对症下药"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "出谋划策"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "四面八方"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "首当其冲"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿鼻地狱"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿党比周"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿党相为"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿狗阿猫"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿姑阿翁"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿家阿翁"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿娇金屋"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿猫阿狗"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿弥陀佛"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿毗地狱"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿平绝倒"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿其所好"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿世盗名"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿世媚俗"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿世取容"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿意取容"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿谀谄媚"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿谀逢迎"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿谀奉承"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "阿谀取容"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀哀父母"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀哀欲绝"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀兵必胜"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀而不伤"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀感天地"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀感顽艳"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀感中年"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀告宾服"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀鸿遍地"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀鸿遍野"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀毁骨立"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀毁瘠立"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀梨蒸食"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀莫大于心死"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀声叹气"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀丝豪竹"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀思如潮"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀天叫地"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "哀痛欲绝"
  },
  {
    "category": "成语",
    "difficulty": "hard",
    "word": "唉声叹气"
  }
];
